//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websitefinal.productlist {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductClass", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_descField;
        
        private System.DateTime Prod_eff_dateField;
        
        private System.DateTime Prod_end_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Service_IDField;
        
        private decimal RateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Product_ID {
            get {
                return this.Product_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_IDField, value) != true)) {
                    this.Product_IDField = value;
                    this.RaisePropertyChanged("Product_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Product_name {
            get {
                return this.Product_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_nameField, value) != true)) {
                    this.Product_nameField = value;
                    this.RaisePropertyChanged("Product_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Product_desc {
            get {
                return this.Product_descField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_descField, value) != true)) {
                    this.Product_descField = value;
                    this.RaisePropertyChanged("Product_desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Prod_eff_date {
            get {
                return this.Prod_eff_dateField;
            }
            set {
                if ((this.Prod_eff_dateField.Equals(value) != true)) {
                    this.Prod_eff_dateField = value;
                    this.RaisePropertyChanged("Prod_eff_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime Prod_end_date {
            get {
                return this.Prod_end_dateField;
            }
            set {
                if ((this.Prod_end_dateField.Equals(value) != true)) {
                    this.Prod_end_dateField = value;
                    this.RaisePropertyChanged("Prod_end_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Service_ID {
            get {
                return this.Service_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Service_IDField, value) != true)) {
                    this.Service_IDField = value;
                    this.RaisePropertyChanged("Service_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductRate", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductRate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_IDField;
        
        private decimal RateField;
        
        private System.DateTime Rate_eff_dateField;
        
        private System.DateTime Rate_end_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string State_codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Product_ID {
            get {
                return this.Product_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_IDField, value) != true)) {
                    this.Product_IDField = value;
                    this.RaisePropertyChanged("Product_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Rate_eff_date {
            get {
                return this.Rate_eff_dateField;
            }
            set {
                if ((this.Rate_eff_dateField.Equals(value) != true)) {
                    this.Rate_eff_dateField = value;
                    this.RaisePropertyChanged("Rate_eff_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Rate_end_date {
            get {
                return this.Rate_end_dateField;
            }
            set {
                if ((this.Rate_end_dateField.Equals(value) != true)) {
                    this.Rate_end_dateField = value;
                    this.RaisePropertyChanged("Rate_end_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string State_code {
            get {
                return this.State_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.State_codeField, value) != true)) {
                    this.State_codeField = value;
                    this.RaisePropertyChanged("State_code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="productlist.GetAllProductsSoap")]
    public interface GetAllProductsSoap {
        
        // CODEGEN: Generating message contract since element name GetAllProductsListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProductsList", ReplyAction="*")]
        websitefinal.productlist.GetAllProductsListResponse GetAllProductsList(websitefinal.productlist.GetAllProductsListRequest request);
        
        // CODEGEN: Generating message contract since element name serviceid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsByServiceID", ReplyAction="*")]
        websitefinal.productlist.GetProductsByServiceIDResponse GetProductsByServiceID(websitefinal.productlist.GetProductsByServiceIDRequest request);
        
        // CODEGEN: Generating message contract since element name serviceid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsByZipAndServiceID", ReplyAction="*")]
        websitefinal.productlist.GetProductsByZipAndServiceIDResponse GetProductsByZipAndServiceID(websitefinal.productlist.GetProductsByZipAndServiceIDRequest request);
        
        // CODEGEN: Generating message contract since element name state_code from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEnterpriseProducts", ReplyAction="*")]
        websitefinal.productlist.GetEnterpriseProductsResponse GetEnterpriseProducts(websitefinal.productlist.GetEnterpriseProductsRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductRatesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductRates", ReplyAction="*")]
        websitefinal.productlist.GetProductRatesResponse GetProductRates(websitefinal.productlist.GetProductRatesRequest request);
        
        // CODEGEN: Generating message contract since element name Product_name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductDescriptionByProductName", ReplyAction="*")]
        websitefinal.productlist.GetProductDescriptionByProductNameResponse GetProductDescriptionByProductName(websitefinal.productlist.GetProductDescriptionByProductNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProductsList", Namespace="http://tempuri.org/", Order=0)]
        public websitefinal.productlist.GetAllProductsListRequestBody Body;
        
        public GetAllProductsListRequest() {
        }
        
        public GetAllProductsListRequest(websitefinal.productlist.GetAllProductsListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllProductsListRequestBody {
        
        public GetAllProductsListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProductsListResponse", Namespace="http://tempuri.org/", Order=0)]
        public websitefinal.productlist.GetAllProductsListResponseBody Body;
        
        public GetAllProductsListResponse() {
        }
        
        public GetAllProductsListResponse(websitefinal.productlist.GetAllProductsListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProductsListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public websitefinal.productlist.ProductClass[] GetAllProductsListResult;
        
        public GetAllProductsListResponseBody() {
        }
        
        public GetAllProductsListResponseBody(websitefinal.productlist.ProductClass[] GetAllProductsListResult) {
            this.GetAllProductsListResult = GetAllProductsListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsByServiceIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsByServiceID", Namespace="http://tempuri.org/", Order=0)]
        public websitefinal.productlist.GetProductsByServiceIDRequestBody Body;
        
        public GetProductsByServiceIDRequest() {
        }
        
        public GetProductsByServiceIDRequest(websitefinal.productlist.GetProductsByServiceIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsByServiceIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serviceid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string state_code;
        
        public GetProductsByServiceIDRequestBody() {
        }
        
        public GetProductsByServiceIDRequestBody(string serviceid, string state_code) {
            this.serviceid = serviceid;
            this.state_code = state_code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsByServiceIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsByServiceIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public websitefinal.productlist.GetProductsByServiceIDResponseBody Body;
        
        public GetProductsByServiceIDResponse() {
        }
        
        public GetProductsByServiceIDResponse(websitefinal.productlist.GetProductsByServiceIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsByServiceIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public websitefinal.productlist.ProductClass[] GetProductsByServiceIDResult;
        
        public GetProductsByServiceIDResponseBody() {
        }
        
        public GetProductsByServiceIDResponseBody(websitefinal.productlist.ProductClass[] GetProductsByServiceIDResult) {
            this.GetProductsByServiceIDResult = GetProductsByServiceIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsByZipAndServiceIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsByZipAndServiceID", Namespace="http://tempuri.org/", Order=0)]
        public websitefinal.productlist.GetProductsByZipAndServiceIDRequestBody Body;
        
        public GetProductsByZipAndServiceIDRequest() {
        }
        
        public GetProductsByZipAndServiceIDRequest(websitefinal.productlist.GetProductsByZipAndServiceIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsByZipAndServiceIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serviceid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int zip;
        
        public GetProductsByZipAndServiceIDRequestBody() {
        }
        
        public GetProductsByZipAndServiceIDRequestBody(string serviceid, int zip) {
            this.serviceid = serviceid;
            this.zip = zip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsByZipAndServiceIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsByZipAndServiceIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public websitefinal.productlist.GetProductsByZipAndServiceIDResponseBody Body;
        
        public GetProductsByZipAndServiceIDResponse() {
        }
        
        public GetProductsByZipAndServiceIDResponse(websitefinal.productlist.GetProductsByZipAndServiceIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsByZipAndServiceIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public websitefinal.productlist.ProductClass[] GetProductsByZipAndServiceIDResult;
        
        public GetProductsByZipAndServiceIDResponseBody() {
        }
        
        public GetProductsByZipAndServiceIDResponseBody(websitefinal.productlist.ProductClass[] GetProductsByZipAndServiceIDResult) {
            this.GetProductsByZipAndServiceIDResult = GetProductsByZipAndServiceIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEnterpriseProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEnterpriseProducts", Namespace="http://tempuri.org/", Order=0)]
        public websitefinal.productlist.GetEnterpriseProductsRequestBody Body;
        
        public GetEnterpriseProductsRequest() {
        }
        
        public GetEnterpriseProductsRequest(websitefinal.productlist.GetEnterpriseProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEnterpriseProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string state_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int zip;
        
        public GetEnterpriseProductsRequestBody() {
        }
        
        public GetEnterpriseProductsRequestBody(string state_code, int zip) {
            this.state_code = state_code;
            this.zip = zip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEnterpriseProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEnterpriseProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public websitefinal.productlist.GetEnterpriseProductsResponseBody Body;
        
        public GetEnterpriseProductsResponse() {
        }
        
        public GetEnterpriseProductsResponse(websitefinal.productlist.GetEnterpriseProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEnterpriseProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public websitefinal.productlist.ProductClass[] GetEnterpriseProductsResult;
        
        public GetEnterpriseProductsResponseBody() {
        }
        
        public GetEnterpriseProductsResponseBody(websitefinal.productlist.ProductClass[] GetEnterpriseProductsResult) {
            this.GetEnterpriseProductsResult = GetEnterpriseProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductRates", Namespace="http://tempuri.org/", Order=0)]
        public websitefinal.productlist.GetProductRatesRequestBody Body;
        
        public GetProductRatesRequest() {
        }
        
        public GetProductRatesRequest(websitefinal.productlist.GetProductRatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductRatesRequestBody {
        
        public GetProductRatesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductRatesResponse", Namespace="http://tempuri.org/", Order=0)]
        public websitefinal.productlist.GetProductRatesResponseBody Body;
        
        public GetProductRatesResponse() {
        }
        
        public GetProductRatesResponse(websitefinal.productlist.GetProductRatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductRatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public websitefinal.productlist.ProductRate[] GetProductRatesResult;
        
        public GetProductRatesResponseBody() {
        }
        
        public GetProductRatesResponseBody(websitefinal.productlist.ProductRate[] GetProductRatesResult) {
            this.GetProductRatesResult = GetProductRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductDescriptionByProductNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductDescriptionByProductName", Namespace="http://tempuri.org/", Order=0)]
        public websitefinal.productlist.GetProductDescriptionByProductNameRequestBody Body;
        
        public GetProductDescriptionByProductNameRequest() {
        }
        
        public GetProductDescriptionByProductNameRequest(websitefinal.productlist.GetProductDescriptionByProductNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductDescriptionByProductNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Product_name;
        
        public GetProductDescriptionByProductNameRequestBody() {
        }
        
        public GetProductDescriptionByProductNameRequestBody(string Product_name) {
            this.Product_name = Product_name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductDescriptionByProductNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductDescriptionByProductNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public websitefinal.productlist.GetProductDescriptionByProductNameResponseBody Body;
        
        public GetProductDescriptionByProductNameResponse() {
        }
        
        public GetProductDescriptionByProductNameResponse(websitefinal.productlist.GetProductDescriptionByProductNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductDescriptionByProductNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public websitefinal.productlist.ProductClass[] GetProductDescriptionByProductNameResult;
        
        public GetProductDescriptionByProductNameResponseBody() {
        }
        
        public GetProductDescriptionByProductNameResponseBody(websitefinal.productlist.ProductClass[] GetProductDescriptionByProductNameResult) {
            this.GetProductDescriptionByProductNameResult = GetProductDescriptionByProductNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetAllProductsSoapChannel : websitefinal.productlist.GetAllProductsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllProductsSoapClient : System.ServiceModel.ClientBase<websitefinal.productlist.GetAllProductsSoap>, websitefinal.productlist.GetAllProductsSoap {
        
        public GetAllProductsSoapClient() {
        }
        
        public GetAllProductsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetAllProductsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetAllProductsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetAllProductsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        websitefinal.productlist.GetAllProductsListResponse websitefinal.productlist.GetAllProductsSoap.GetAllProductsList(websitefinal.productlist.GetAllProductsListRequest request) {
            return base.Channel.GetAllProductsList(request);
        }
        
        public websitefinal.productlist.ProductClass[] GetAllProductsList() {
            websitefinal.productlist.GetAllProductsListRequest inValue = new websitefinal.productlist.GetAllProductsListRequest();
            inValue.Body = new websitefinal.productlist.GetAllProductsListRequestBody();
            websitefinal.productlist.GetAllProductsListResponse retVal = ((websitefinal.productlist.GetAllProductsSoap)(this)).GetAllProductsList(inValue);
            return retVal.Body.GetAllProductsListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        websitefinal.productlist.GetProductsByServiceIDResponse websitefinal.productlist.GetAllProductsSoap.GetProductsByServiceID(websitefinal.productlist.GetProductsByServiceIDRequest request) {
            return base.Channel.GetProductsByServiceID(request);
        }
        
        public websitefinal.productlist.ProductClass[] GetProductsByServiceID(string serviceid, string state_code) {
            websitefinal.productlist.GetProductsByServiceIDRequest inValue = new websitefinal.productlist.GetProductsByServiceIDRequest();
            inValue.Body = new websitefinal.productlist.GetProductsByServiceIDRequestBody();
            inValue.Body.serviceid = serviceid;
            inValue.Body.state_code = state_code;
            websitefinal.productlist.GetProductsByServiceIDResponse retVal = ((websitefinal.productlist.GetAllProductsSoap)(this)).GetProductsByServiceID(inValue);
            return retVal.Body.GetProductsByServiceIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        websitefinal.productlist.GetProductsByZipAndServiceIDResponse websitefinal.productlist.GetAllProductsSoap.GetProductsByZipAndServiceID(websitefinal.productlist.GetProductsByZipAndServiceIDRequest request) {
            return base.Channel.GetProductsByZipAndServiceID(request);
        }
        
        public websitefinal.productlist.ProductClass[] GetProductsByZipAndServiceID(string serviceid, int zip) {
            websitefinal.productlist.GetProductsByZipAndServiceIDRequest inValue = new websitefinal.productlist.GetProductsByZipAndServiceIDRequest();
            inValue.Body = new websitefinal.productlist.GetProductsByZipAndServiceIDRequestBody();
            inValue.Body.serviceid = serviceid;
            inValue.Body.zip = zip;
            websitefinal.productlist.GetProductsByZipAndServiceIDResponse retVal = ((websitefinal.productlist.GetAllProductsSoap)(this)).GetProductsByZipAndServiceID(inValue);
            return retVal.Body.GetProductsByZipAndServiceIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        websitefinal.productlist.GetEnterpriseProductsResponse websitefinal.productlist.GetAllProductsSoap.GetEnterpriseProducts(websitefinal.productlist.GetEnterpriseProductsRequest request) {
            return base.Channel.GetEnterpriseProducts(request);
        }
        
        public websitefinal.productlist.ProductClass[] GetEnterpriseProducts(string state_code, int zip) {
            websitefinal.productlist.GetEnterpriseProductsRequest inValue = new websitefinal.productlist.GetEnterpriseProductsRequest();
            inValue.Body = new websitefinal.productlist.GetEnterpriseProductsRequestBody();
            inValue.Body.state_code = state_code;
            inValue.Body.zip = zip;
            websitefinal.productlist.GetEnterpriseProductsResponse retVal = ((websitefinal.productlist.GetAllProductsSoap)(this)).GetEnterpriseProducts(inValue);
            return retVal.Body.GetEnterpriseProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        websitefinal.productlist.GetProductRatesResponse websitefinal.productlist.GetAllProductsSoap.GetProductRates(websitefinal.productlist.GetProductRatesRequest request) {
            return base.Channel.GetProductRates(request);
        }
        
        public websitefinal.productlist.ProductRate[] GetProductRates() {
            websitefinal.productlist.GetProductRatesRequest inValue = new websitefinal.productlist.GetProductRatesRequest();
            inValue.Body = new websitefinal.productlist.GetProductRatesRequestBody();
            websitefinal.productlist.GetProductRatesResponse retVal = ((websitefinal.productlist.GetAllProductsSoap)(this)).GetProductRates(inValue);
            return retVal.Body.GetProductRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        websitefinal.productlist.GetProductDescriptionByProductNameResponse websitefinal.productlist.GetAllProductsSoap.GetProductDescriptionByProductName(websitefinal.productlist.GetProductDescriptionByProductNameRequest request) {
            return base.Channel.GetProductDescriptionByProductName(request);
        }
        
        public websitefinal.productlist.ProductClass[] GetProductDescriptionByProductName(string Product_name) {
            websitefinal.productlist.GetProductDescriptionByProductNameRequest inValue = new websitefinal.productlist.GetProductDescriptionByProductNameRequest();
            inValue.Body = new websitefinal.productlist.GetProductDescriptionByProductNameRequestBody();
            inValue.Body.Product_name = Product_name;
            websitefinal.productlist.GetProductDescriptionByProductNameResponse retVal = ((websitefinal.productlist.GetAllProductsSoap)(this)).GetProductDescriptionByProductName(inValue);
            return retVal.Body.GetProductDescriptionByProductNameResult;
        }
    }
}
