//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name customer_id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/product_service", ReplyAction="*")]
        WebApplication1.ServiceReference2.product_serviceResponse product_service(WebApplication1.ServiceReference2.product_serviceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class product_serviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="product_service", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference2.product_serviceRequestBody Body;
        
        public product_serviceRequest() {
        }
        
        public product_serviceRequest(WebApplication1.ServiceReference2.product_serviceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class product_serviceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customer_id;
        
        public product_serviceRequestBody() {
        }
        
        public product_serviceRequestBody(string customer_id) {
            this.customer_id = customer_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class product_serviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="product_serviceResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference2.product_serviceResponseBody Body;
        
        public product_serviceResponse() {
        }
        
        public product_serviceResponse(WebApplication1.ServiceReference2.product_serviceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class product_serviceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string product_serviceResult;
        
        public product_serviceResponseBody() {
        }
        
        public product_serviceResponseBody(string product_serviceResult) {
            this.product_serviceResult = product_serviceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WebApplication1.ServiceReference2.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference2.Service1Soap>, WebApplication1.ServiceReference2.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference2.product_serviceResponse WebApplication1.ServiceReference2.Service1Soap.product_service(WebApplication1.ServiceReference2.product_serviceRequest request) {
            return base.Channel.product_service(request);
        }
        
        public string product_service(string customer_id) {
            WebApplication1.ServiceReference2.product_serviceRequest inValue = new WebApplication1.ServiceReference2.product_serviceRequest();
            inValue.Body = new WebApplication1.ServiceReference2.product_serviceRequestBody();
            inValue.Body.customer_id = customer_id;
            WebApplication1.ServiceReference2.product_serviceResponse retVal = ((WebApplication1.ServiceReference2.Service1Soap)(this)).product_service(inValue);
            return retVal.Body.product_serviceResult;
        }
    }
}
