//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mywebsite.getStatus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dao.com/", ConfigurationName="getStatus.CustDao1")]
    public interface CustDao1 {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://dao.com/CustDao1/getCustOrdersRequest", ReplyAction="http://dao.com/CustDao1/getCustOrdersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        mywebsite.getStatus.getCustOrdersResponse getCustOrders(mywebsite.getStatus.getCustOrdersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://dao.com/CustDao1/getCustOrders1Request", ReplyAction="http://dao.com/CustDao1/getCustOrders1Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        mywebsite.getStatus.getCustOrders1Response getCustOrders1(mywebsite.getStatus.getCustOrders1Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://dao.com/CustDao1/getCustOrders2Request", ReplyAction="http://dao.com/CustDao1/getCustOrders2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        mywebsite.getStatus.getCustOrders2Response getCustOrders2(mywebsite.getStatus.getCustOrders2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://dao.com/CustDao1/getCustOrders3Request", ReplyAction="http://dao.com/CustDao1/getCustOrders3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        mywebsite.getStatus.getCustOrders3Response getCustOrders3(mywebsite.getStatus.getCustOrders3Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://dao.com/CustDao1/getCustOrders4Request", ReplyAction="http://dao.com/CustDao1/getCustOrders4Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        mywebsite.getStatus.getCustOrders4Response getCustOrders4(mywebsite.getStatus.getCustOrders4Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://dao.com/CustDao1/getCustOrders5Request", ReplyAction="http://dao.com/CustDao1/getCustOrders5Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        mywebsite.getStatus.getCustOrders5Response getCustOrders5(mywebsite.getStatus.getCustOrders5Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dao.com/")]
    public partial class custOrders : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string billPaymentMethodField;
        
        private int billingAddIDField;
        
        private string customerEmailIDField;
        
        private string customerFnameField;
        
        private int customerIDField;
        
        private string customerLnameField;
        
        private long customerMobNoField;
        
        private string customerStatusField;
        
        private string customerTypeField;
        
        private int serviceAddIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string billPaymentMethod {
            get {
                return this.billPaymentMethodField;
            }
            set {
                this.billPaymentMethodField = value;
                this.RaisePropertyChanged("billPaymentMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int billingAddID {
            get {
                return this.billingAddIDField;
            }
            set {
                this.billingAddIDField = value;
                this.RaisePropertyChanged("billingAddID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string customerEmailID {
            get {
                return this.customerEmailIDField;
            }
            set {
                this.customerEmailIDField = value;
                this.RaisePropertyChanged("customerEmailID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string customerFname {
            get {
                return this.customerFnameField;
            }
            set {
                this.customerFnameField = value;
                this.RaisePropertyChanged("customerFname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string customerLname {
            get {
                return this.customerLnameField;
            }
            set {
                this.customerLnameField = value;
                this.RaisePropertyChanged("customerLname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long customerMobNo {
            get {
                return this.customerMobNoField;
            }
            set {
                this.customerMobNoField = value;
                this.RaisePropertyChanged("customerMobNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string customerStatus {
            get {
                return this.customerStatusField;
            }
            set {
                this.customerStatusField = value;
                this.RaisePropertyChanged("customerStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string customerType {
            get {
                return this.customerTypeField;
            }
            set {
                this.customerTypeField = value;
                this.RaisePropertyChanged("customerType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int serviceAddID {
            get {
                return this.serviceAddIDField;
            }
            set {
                this.serviceAddIDField = value;
                this.RaisePropertyChanged("serviceAddID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dao.com/")]
    public partial class custOrders5 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceIDField;
        
        private string serviceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string serviceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
                this.RaisePropertyChanged("serviceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("serviceName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dao.com/")]
    public partial class custOrders4 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int customerIDField;
        
        private string serviceCurrentStatusField;
        
        private System.DateTime serviceEffectiveDateField;
        
        private bool serviceEffectiveDateFieldSpecified;
        
        private System.DateTime serviceEndDateField;
        
        private bool serviceEndDateFieldSpecified;
        
        private string serviceIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string serviceCurrentStatus {
            get {
                return this.serviceCurrentStatusField;
            }
            set {
                this.serviceCurrentStatusField = value;
                this.RaisePropertyChanged("serviceCurrentStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime serviceEffectiveDate {
            get {
                return this.serviceEffectiveDateField;
            }
            set {
                this.serviceEffectiveDateField = value;
                this.RaisePropertyChanged("serviceEffectiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serviceEffectiveDateSpecified {
            get {
                return this.serviceEffectiveDateFieldSpecified;
            }
            set {
                this.serviceEffectiveDateFieldSpecified = value;
                this.RaisePropertyChanged("serviceEffectiveDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime serviceEndDate {
            get {
                return this.serviceEndDateField;
            }
            set {
                this.serviceEndDateField = value;
                this.RaisePropertyChanged("serviceEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serviceEndDateSpecified {
            get {
                return this.serviceEndDateFieldSpecified;
            }
            set {
                this.serviceEndDateFieldSpecified = value;
                this.RaisePropertyChanged("serviceEndDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string serviceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
                this.RaisePropertyChanged("serviceID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dao.com/")]
    public partial class custOrders3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int orderIDField;
        
        private string productDescriptionField;
        
        private string productIDField;
        
        private int productQuantityField;
        
        private string serviceIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int orderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
                this.RaisePropertyChanged("orderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string productDescription {
            get {
                return this.productDescriptionField;
            }
            set {
                this.productDescriptionField = value;
                this.RaisePropertyChanged("productDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string productID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
                this.RaisePropertyChanged("productID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int productQuantity {
            get {
                return this.productQuantityField;
            }
            set {
                this.productQuantityField = value;
                this.RaisePropertyChanged("productQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string serviceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
                this.RaisePropertyChanged("serviceID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dao.com/")]
    public partial class custOrders2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime completionDateField;
        
        private bool completionDateFieldSpecified;
        
        private int customerIDField;
        
        private System.DateTime dueDateField;
        
        private bool dueDateFieldSpecified;
        
        private System.DateTime negotiationDateField;
        
        private bool negotiationDateFieldSpecified;
        
        private int orderIdField;
        
        private string orderStatusField;
        
        private string orderTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime completionDate {
            get {
                return this.completionDateField;
            }
            set {
                this.completionDateField = value;
                this.RaisePropertyChanged("completionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completionDateSpecified {
            get {
                return this.completionDateFieldSpecified;
            }
            set {
                this.completionDateFieldSpecified = value;
                this.RaisePropertyChanged("completionDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime dueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
                this.RaisePropertyChanged("dueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueDateSpecified {
            get {
                return this.dueDateFieldSpecified;
            }
            set {
                this.dueDateFieldSpecified = value;
                this.RaisePropertyChanged("dueDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime negotiationDate {
            get {
                return this.negotiationDateField;
            }
            set {
                this.negotiationDateField = value;
                this.RaisePropertyChanged("negotiationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool negotiationDateSpecified {
            get {
                return this.negotiationDateFieldSpecified;
            }
            set {
                this.negotiationDateFieldSpecified = value;
                this.RaisePropertyChanged("negotiationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("orderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string orderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("orderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string orderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
                this.RaisePropertyChanged("orderType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dao.com/")]
    public partial class custOrders1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addLine1Field;
        
        private string addLine2Field;
        
        private int addressIDField;
        
        private string cityField;
        
        private string stateField;
        
        private string stateCodeField;
        
        private int zipCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string addLine1 {
            get {
                return this.addLine1Field;
            }
            set {
                this.addLine1Field = value;
                this.RaisePropertyChanged("addLine1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string addLine2 {
            get {
                return this.addLine2Field;
            }
            set {
                this.addLine2Field = value;
                this.RaisePropertyChanged("addLine2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int addressID {
            get {
                return this.addressIDField;
            }
            set {
                this.addressIDField = value;
                this.RaisePropertyChanged("addressID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string stateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
                this.RaisePropertyChanged("stateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("zipCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustOrders", WrapperNamespace="http://dao.com/", IsWrapped=true)]
    public partial class getCustOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dao.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getCustOrdersRequest() {
        }
        
        public getCustOrdersRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustOrdersResponse", WrapperNamespace="http://dao.com/", IsWrapped=true)]
    public partial class getCustOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dao.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mywebsite.getStatus.custOrders[] @return;
        
        public getCustOrdersResponse() {
        }
        
        public getCustOrdersResponse(mywebsite.getStatus.custOrders[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustOrders1", WrapperNamespace="http://dao.com/", IsWrapped=true)]
    public partial class getCustOrders1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dao.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getCustOrders1Request() {
        }
        
        public getCustOrders1Request(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustOrders1Response", WrapperNamespace="http://dao.com/", IsWrapped=true)]
    public partial class getCustOrders1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dao.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mywebsite.getStatus.custOrders1[] @return;
        
        public getCustOrders1Response() {
        }
        
        public getCustOrders1Response(mywebsite.getStatus.custOrders1[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustOrders2", WrapperNamespace="http://dao.com/", IsWrapped=true)]
    public partial class getCustOrders2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dao.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getCustOrders2Request() {
        }
        
        public getCustOrders2Request(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustOrders2Response", WrapperNamespace="http://dao.com/", IsWrapped=true)]
    public partial class getCustOrders2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dao.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mywebsite.getStatus.custOrders2[] @return;
        
        public getCustOrders2Response() {
        }
        
        public getCustOrders2Response(mywebsite.getStatus.custOrders2[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustOrders3", WrapperNamespace="http://dao.com/", IsWrapped=true)]
    public partial class getCustOrders3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dao.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getCustOrders3Request() {
        }
        
        public getCustOrders3Request(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustOrders3Response", WrapperNamespace="http://dao.com/", IsWrapped=true)]
    public partial class getCustOrders3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dao.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mywebsite.getStatus.custOrders3[] @return;
        
        public getCustOrders3Response() {
        }
        
        public getCustOrders3Response(mywebsite.getStatus.custOrders3[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustOrders4", WrapperNamespace="http://dao.com/", IsWrapped=true)]
    public partial class getCustOrders4Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dao.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getCustOrders4Request() {
        }
        
        public getCustOrders4Request(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustOrders4Response", WrapperNamespace="http://dao.com/", IsWrapped=true)]
    public partial class getCustOrders4Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dao.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mywebsite.getStatus.custOrders4[] @return;
        
        public getCustOrders4Response() {
        }
        
        public getCustOrders4Response(mywebsite.getStatus.custOrders4[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustOrders5", WrapperNamespace="http://dao.com/", IsWrapped=true)]
    public partial class getCustOrders5Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dao.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getCustOrders5Request() {
        }
        
        public getCustOrders5Request(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustOrders5Response", WrapperNamespace="http://dao.com/", IsWrapped=true)]
    public partial class getCustOrders5Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dao.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mywebsite.getStatus.custOrders5[] @return;
        
        public getCustOrders5Response() {
        }
        
        public getCustOrders5Response(mywebsite.getStatus.custOrders5[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustDao1Channel : mywebsite.getStatus.CustDao1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustDao1Client : System.ServiceModel.ClientBase<mywebsite.getStatus.CustDao1>, mywebsite.getStatus.CustDao1 {
        
        public CustDao1Client() {
        }
        
        public CustDao1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustDao1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustDao1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustDao1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mywebsite.getStatus.getCustOrdersResponse mywebsite.getStatus.CustDao1.getCustOrders(mywebsite.getStatus.getCustOrdersRequest request) {
            return base.Channel.getCustOrders(request);
        }
        
        public mywebsite.getStatus.custOrders[] getCustOrders(int arg0) {
            mywebsite.getStatus.getCustOrdersRequest inValue = new mywebsite.getStatus.getCustOrdersRequest();
            inValue.arg0 = arg0;
            mywebsite.getStatus.getCustOrdersResponse retVal = ((mywebsite.getStatus.CustDao1)(this)).getCustOrders(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mywebsite.getStatus.getCustOrders1Response mywebsite.getStatus.CustDao1.getCustOrders1(mywebsite.getStatus.getCustOrders1Request request) {
            return base.Channel.getCustOrders1(request);
        }
        
        public mywebsite.getStatus.custOrders1[] getCustOrders1(int arg0) {
            mywebsite.getStatus.getCustOrders1Request inValue = new mywebsite.getStatus.getCustOrders1Request();
            inValue.arg0 = arg0;
            mywebsite.getStatus.getCustOrders1Response retVal = ((mywebsite.getStatus.CustDao1)(this)).getCustOrders1(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mywebsite.getStatus.getCustOrders2Response mywebsite.getStatus.CustDao1.getCustOrders2(mywebsite.getStatus.getCustOrders2Request request) {
            return base.Channel.getCustOrders2(request);
        }
        
        public mywebsite.getStatus.custOrders2[] getCustOrders2(int arg0) {
            mywebsite.getStatus.getCustOrders2Request inValue = new mywebsite.getStatus.getCustOrders2Request();
            inValue.arg0 = arg0;
            mywebsite.getStatus.getCustOrders2Response retVal = ((mywebsite.getStatus.CustDao1)(this)).getCustOrders2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mywebsite.getStatus.getCustOrders3Response mywebsite.getStatus.CustDao1.getCustOrders3(mywebsite.getStatus.getCustOrders3Request request) {
            return base.Channel.getCustOrders3(request);
        }
        
        public mywebsite.getStatus.custOrders3[] getCustOrders3(int arg0) {
            mywebsite.getStatus.getCustOrders3Request inValue = new mywebsite.getStatus.getCustOrders3Request();
            inValue.arg0 = arg0;
            mywebsite.getStatus.getCustOrders3Response retVal = ((mywebsite.getStatus.CustDao1)(this)).getCustOrders3(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mywebsite.getStatus.getCustOrders4Response mywebsite.getStatus.CustDao1.getCustOrders4(mywebsite.getStatus.getCustOrders4Request request) {
            return base.Channel.getCustOrders4(request);
        }
        
        public mywebsite.getStatus.custOrders4[] getCustOrders4(int arg0) {
            mywebsite.getStatus.getCustOrders4Request inValue = new mywebsite.getStatus.getCustOrders4Request();
            inValue.arg0 = arg0;
            mywebsite.getStatus.getCustOrders4Response retVal = ((mywebsite.getStatus.CustDao1)(this)).getCustOrders4(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mywebsite.getStatus.getCustOrders5Response mywebsite.getStatus.CustDao1.getCustOrders5(mywebsite.getStatus.getCustOrders5Request request) {
            return base.Channel.getCustOrders5(request);
        }
        
        public mywebsite.getStatus.custOrders5[] getCustOrders5(int arg0) {
            mywebsite.getStatus.getCustOrders5Request inValue = new mywebsite.getStatus.getCustOrders5Request();
            inValue.arg0 = arg0;
            mywebsite.getStatus.getCustOrders5Response retVal = ((mywebsite.getStatus.CustDao1)(this)).getCustOrders5(inValue);
            return retVal.@return;
        }
    }
}
